function [calib_const] = calib_set_const(tx_loc,rx_loc,tx_orient,rx_orient,C,...
    carrier_frequency,FI,max_offset,F,x_range,y_range,x_step,y_step,AS_vec,DS_vec)
% set parameter for calib
    f = (-14.5:1:14.5)*FI+carrier_frequency;
    calib_const = struct('tx_loc',tx_loc,'rx_loc',rx_loc,'tx_orient',tx_orient, ...
        'rx_orient',rx_orient,'C',C,'f',f,'fc',carrier_frequency,'max_offset',max_offset,...
        'F',F,'x_range',x_range,'y_range',y_range,'x_step',x_step,'y_step',y_step,...
        'AS_vec',AS_vec,'DS_vec',DS_vec);
end

